[package]
name = "ACSCG"
version = "0.1.0"
authors = ["crome <crome110mine@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = "*"
serde_derive = "*"
serde_json = "1"
num-traits = "*"
num-derive = "*"